# Generated by Django 3.2.15 on 2022-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipetag",
            constraint=models.UniqueConstraint(
                fields=("tag", "recipe"), name="unique_tag_recipes"
            ),
        ),
    ]
